apiVersion: v2
name: auth-service
type: application
version: 1.0.0
description: Auth service Helm chart
appVersion: 1.0.0

dependencies:
  - name: mongodb
    version: 18.1.9
    repository: https://charts.bitnami.com/bitnami
