replicaCount: 1

environment: ""

image:
  repository: vasapolrittideah/money-tracker-api-auth-service
  tag: "latest"
  pullPolicy: IfNotPresent

vault:
  server: "http://vault.vault.svc.cluster.local:8200"
  path: "secret"
  auth:
    mountPath: "kubernetes"
    role: "auth-service"

service:
  address: 0.0.0.0
  port: 9001

serviceAccount:
  create: true
  name: ""

mongodb:
  fullnameOverride: money-tracker-api-auth-mongodb
  architecture: standalone
  auth:
    enabled: true
    rootUser: root
    rootPassword: admin
    usernames: ["auth-user"]
    passwords: ["auth-password"]
    databases: ["auth-db"]
  persistence:
    enabled: true
    size: 5Gi
