apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "auth-service.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "auth-service.fullname" . }}-vault
    kind: SecretStore

  target:
    name: {{ include "auth-service.fullname" . }}-secrets
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: auth-service/mongodb
    - extract:
        key: auth-service/jwt
    - extract:
        key: auth-service/smtp
