apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "auth-service.fullname" . }}-vault
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.path }}
      version: "v2"
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.auth.mountPath }}
          role: {{ .Values.vault.auth.role }}
          serviceAccountRef:
            name: {{ include "auth-service.serviceAccountName" . }}
            audiences:
              - vault
